mkdir "%1\bin"
mkdir "%1\lib"
mkdir "%1\include\commonc++"
copy /y "debug\*.dll" "%1\bin"
copy /y "debug\*.exe" "%1\bin"
copy /y "release\*.dll" "%1\bin"
copy /y "release\*.exe" "%1\bin"
copy /y "debug\*.lib" "%1\lib"
copy /y "release\*.lib" "%1\lib"
copy /y "lib\commonc++\*.h++" "%1\include\commonc++"
